fix(test): fix testing svelte lib error
i got this error:
src/lib/PostsTable.svelte.test.ts [ src/lib/PostsTable.svelte.test.ts ]
Error: Failed to import test file /home/danielvelkov/repos/odin-blog/dans-coding-world/libs/blog-admin/features/posts-table/src/lib/PostsTable.svelte.test.ts
Caused by: TypeError: error loading dynamically imported module: http://localhost:63315/@fs/home/danielvelkov/repos/odin-blog/dans-coding-world/node_modules/.vite/libs/blog-admin/features/posts-table/vitest/d2a04d71301a8915217dd5faf81d12cffd6cd958/deps/svelte_internal_flags_legacy.js?v=30d99502

adding this line to config file fixed it